# Generated by Django 5.2.12 on 2026-04-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='votos',
        ),
    ]
